[project]
name = 'Secure-Professional-Licensing-Verification'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.continuing-education]
path = 'contracts/continuing-education.clar'
clarity_version = 2
epoch = 2.5

[contracts.license-issuance]
path = 'contracts/license-issuance.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
